### ISSUE TITLE
Fresh installation broken

### ISSUE THREAD

**Issue by fdev31** [mayan-edms/mayan-edms#141] opened 2015-01-14 16:43 UTC
After installation (using Documented way, via venv) If I enter admin credentials, I get this error:

```
TemplateSyntaxError at /

'registration_tags' is not a valid tag library: Template library registration_tags not found, tried django.templatetags.registration_tags,django.contrib.admin.templatetags.registration_tags,django.contrib.comments.templatetags.registration_tags,django.contrib.staticfiles.templatetags.registration_tags,filetransfers.templatetags.registration_tags,mptt.templatetags.registration_tags,compressor.templatetags.registration_tags,rest_framework.templatetags.registration_tags,solo.templatetags.registration_tags,permissions.templatetags.registration_tags,navigation.templatetags.registration_tags,web_theme.templatetags.registration_tags,pagination.templatetags.registration_tags,common.templatetags.registration_tags,dynamic_search.templatetags.registration_tags,acls.templatetags.registration_tags,folders.templatetags.registration_tags,tags.templatetags.registration_tags,documents.templatetags.registration_tags,main.templatetags.registration_tags

Request Method:	GET
Request URL:	http://localhost:8000/
Django Version:	1.6.5
Exception Type:	TemplateSyntaxError
Exception Value:	

'registration_tags' is not a valid tag library: Template library registration_tags not found, tried django.templatetags.registration_tags,django.contrib.admin.templatetags.registration_tags,django.contrib.comments.templatetags.registration_tags,django.contrib.staticfiles.templatetags.registration_tags,filetransfers.templatetags.registration_tags,mptt.templatetags.registration_tags,compressor.templatetags.registration_tags,rest_framework.templatetags.registration_tags,solo.templatetags.registration_tags,permissions.templatetags.registration_tags,navigation.templatetags.registration_tags,web_theme.templatetags.registration_tags,pagination.templatetags.registration_tags,common.templatetags.registration_tags,dynamic_search.templatetags.registration_tags,acls.templatetags.registration_tags,folders.templatetags.registration_tags,tags.templatetags.registration_tags,documents.templatetags.registration_tags,main.templatetags.registration_tags

Exception Location:	/home/fab/pyenv/doc/lib/python2.7/site-packages/django/template/defaulttags.py in load, line 1084
Python Executable:	/home/fab/pyenv/doc/bin/python2
Python Version:	2.7.9
```

**Comment by rosarior** [comment] 2015-01-14 16:48
Is this for the 1.0 version in PyPI or the development version via git?

**Comment by rosarior** [comment] 2015-02-06 20:35
Any change or updates regarding this issue?

**Comment by mbehrle** [comment] 2015-02-10 12:32
No feedback for one month, so closing. Please reopen, if the issue is still valid.

**Closed by mbehrle** 2015-02-10 12:32 UTC
